---
# tasks file for ORACL19c-CIS


# - name: Check OS version and family
#   ansible.builtin.assert:
#       that: (ansible_distribution != 'CentOS' and ansible_os_family == 'RedHat' or ansible_os_family == "Rocky") and ansible_distribution_major_version is version_compare('8', '==')
#       fail_msg: "This role can only be run against Supported OSs. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
#       success_msg: "This role is running against a supported OS {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
#   when:
#       - os_check
#       - not system_is_ec2
#   tags:
#       - always

# - name: Check ansible version
#   ansible.builtin.assert:
#       that: ansible_version.full is version_compare(min_ansible_version, '>=')
#       fail_msg: "You must use Ansible {{ min_ansible_version }} or greater"
#       success_msg: "This role is running a supported version of ansible {{ ansible_version.full }} >= {{ min_ansible_version }}"
#   tags:
#       - always

- name: Run Section 1 tasks
  ansible.builtin.import_tasks: section_1/main.yml
  when:
      - orc19cis_section1
  tags:
      - orc19cis_section1

- name: Run Section 2 tasks
  ansible.builtin.import_tasks: section_2/main.yml
  when:
      - orc19cis_section2
  tags:
      - orc19cis_section2

# - name: Run Section 3 tasks
#   ansible.builtin.import_tasks: section_3/main.yml
#   when:
#       - orc19cis_section3
#   tags:
#       - orc19cis_section3

# - name: Run Section 4 tasks
#   ansible.builtin.import_tasks: section_4/main.yml
#   when:
#       - orc19cis_section4
#   tags:
#       - orc19cis_section4

# - name: run Section 5 tasks
#   ansible.builtin.import_tasks: section_5/main.yml
#   when:
#       - orc19cis_section5
#   tags:
#       - orc19cis_section5

# - name: Run Section 6 tasks
#   ansible.builtin.import_tasks: section_6/main.yml
#   when:
#       - orc19cis_section6
#   tags:
#       - orc19cis_section6


- name: Output Warning count and control IDs affected
  ansible.builtin.debug:
      msg: "You have {{ warn_count }} warning(s) that require investigating that are related to the following benchmark ID(s) {{ warn_control_list }}"
  tags:
      - always
