---

# - name: Get disk facts
#   win_disk_facts:

# - win_command: sqlcmd -S master -i "c:\\temp\\test.sql"
#   register: sqlcmd_out


# - name: 'select from SQL server DB'
#   win_shell: "invoke-sqlcmd -username \"{{db_user}}\" -password \"{{db_pass}}\" -Query \"SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE'\" | Select-Object * -ExcludeProperty ItemArray, Table, RowError, RowState, HasErrors | ConvertTo-Json"
#   register: response



# - name: two batches with dict output
#   community.general.mssql_script:
#     # login_user: "{{ mssql_login_user }}"
#     # login_password: "{{ mssql_login_password }}"
#     login_host: "{{ mssql_host }}"
#     login_port: "{{ mssql_port }}"
#     db: master
#     script: "SELECT 1"
#     scriptdir: 

- name: Run PowerShell script
  win_shell: "C:\\temp\\example.ps1"
  register: ps_output

- name: Display PowerShell script output
  debug:
    var: ps_output.stdout_lines


- name: Run T-SQL query using PowerShell
  win_shell: |
    $query = Get-Content "C:\\temp\\test.sql" -Raw
    $connectionString = "Server=WIN-8C16K368U73;Database=master;Integrated Security=True;"
    Invoke-Sqlcmd -Query $query -ConnectionString $connectionString
  register: sql_output

- name: Display T-SQL query output
  debug:
    var: sql_output.stdout_lines